---
title: "Título del Proyecto"
author: "Autor"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document: 
    number_sections: yes
    toc: yes
    toc_depth: 2
    toc_float: true
---
```{r setup, include=FALSE}
## set output options
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
options(scipen=999)

## load packages
```

# Comprensión del negocio

## Establecimiento de los objetivos del negocio
El primer objetivo del analista es comprender a fondo, desde una perspectiva de negocio, lo que el cliente realmente quiere lograr. A menudo, el cliente tiene muchos objetivos y limitaciones que compiten entre sí y que deben ser equilibrados adecuadamente. El objetivo del analista es descubrir factores importantes al principio del proyecto que pueden influir en el resultado final. Una consecuencia probable de descuidar este paso sería gastar mucho esfuerzo en producir las respuestas correctas a las preguntas equivocadas.

### Contexto
Recopilar la información que se conoce sobre la situación empresarial de la organización al inicio del proyecto. Estos detalles no sólo sirven para identificar más de cerca los objetivos de negocio a alcanzar, sino también para identificar los recursos, tanto humanos como materiales, que pueden ser utilizados o necesarios durante el transcurso del proyecto.

#### Organización
* Desarrollar organigramas que identifiquen las divisiones, departamentos y grupos de proyectos. El organigrama también debe identificar los nombres y responsabilidades de los gerentes
* Identificar a las personas claves y sus roles
* Identificar un patrocinador interno (patrocinador financiero y usuario principal/experto en el dominio)
* Indicar si existe un comité directivo y hacer una lista de sus miembros
* Identificar las unidades de negocio afectadas por el proyecto de minería de datos (por ejemplo, marketing, ventas, finanzas)

#### Problemática
* Identificar el área del problema (por ejemplo, marketing, atención al cliente, desarrollo de negocios, etc.)
* Describir el problema en términos generales
* Comprobar el estado actual del proyecto (por ejemplo, comprobar si ya está claro dentro de la unidad de negocio que se va a realizar un proyecto de minería de datos, o si es necesario promover la minería de datos como una tecnología clave en el negocio).
* Aclarar los requisitos previos del proyecto (por ejemplo, ¿cuál es la motivación del proyecto? ¿El negocio ya utiliza la minería de datos?)
* Si es necesario, preparar presentaciones sobre la minería de datos a la empresa
* Identificar el grupo objetivo para el producto final (por ejemplo, ¿Se espera que entreguemos un informe para la alta gerencia o un sistema para ser utilizado por usuarios inexpertos?)
* Identificar las necesidades y expectativas de los usuarios

#### Soluciones existentes
* Describir cualquier solución que se utilice actualmente para tratar el problema
* Describir las ventajas y desventajas de la solución actual y el nivel de aceptación por parte de los usuarios.

### Objetivos del negocio
Describir el objetivo principal del cliente, desde una perspectiva de negocio. Además del objetivo principal del negocio, normalmente hay un gran número de preguntas comerciales relacionadas que el cliente desea abordar. Por ejemplo, el objetivo principal del negocio podría ser mantener a los clientes actuales mediante la predicción de cuándo son propensos a pasarse a la competencia, mientras que un objetivo secundario del negocio podría ser determinar si las tarifas más bajas afectan sólo a un segmento particular de clientes.

* Describir brevemente el problema a resolver
* Especificar todas las preguntas de negocio con la mayor precisión posible
* Especificar cualquier otro requisito del negocio (por ejemplo, el negocio no quiere perder ningún cliente).
* Especificar los beneficios esperados en términos de negocio
* **Tenga cuidado en fijar metas inalcanzables, hágalas lo más realistas posible**

### Criterios de éxito del negocio
Describir los criterios para un resultado exitoso o útil del proyecto desde el punto de vista empresarial. Esto podría ser bastante específico y fácilmente medible, como la reducción de la rotación de clientes a un cierto nivel, o general y subjetivo, como "dar una visión útil de las relaciones". En este último caso, asegúrese de indicar quién haría el juicio subjetivo.

* Especificar los criterios de éxito del negocio (por ejemplo, mejorar la tasa de respuesta en una campaña de correo en un 10 por ciento y la tasa de registro en un 20 por ciento).
* Identificar quién evalúa los criterios de éxito  

**Cada uno de los criterios de éxito debe estar relacionado con al menos uno de los objetivos de negocio especificados**

Antes de comenzar la evaluación de la situación, usted podría analizar experiencias previas de este problema, ya sea internamente, usando CRISP-DM, o externamente, usando soluciones pre-empaquetadas.

## Evaluación de la situación
Esta tarea implica una investigación más detallada sobre todos los recursos, limitaciones, suposiciones y otros factores que deben ser considerados al determinar la meta del análisis de datos y al desarrollar el plan del proyecto.

### Inventario de recursos
Enumere los recursos disponibles para el proyecto, incluyendo el personal (expertos en negocios y datos, apoyo técnico, expertos en minería de datos), datos (acceso a datos operativos o almacenados), recursos informáticos (plataformas de hardware) y software (herramientas de minería de datos, otro software relevante).  

#### Recursos de hardware
* Identificar el hardware base
* Establecer la disponibilidad del hardware para el proyecto de minería de datos.
* Comprobar si el cronograma de mantenimiento del hardware entra en conflicto con la disponibilidad para el proyecto de minería de datos.

#### Fuentes de datos y conocimientos
* Identificar las fuentes de datos
* Identificar el tipo de fuentes de datos (fuentes en línea, expertos, documentación escrita, etc.)
* Identificar las fuentes de conocimientos
* Identificar el tipo de fuentes de conocimiento (fuentes en línea, expertos, documentación escrita, etc.)
* Revisar las herramientas y técnicas disponibles
* Describir los conocimientos previos (de manera formal o informal)

#### Recursos humanos
* Identificar el patrocinador del proyecto (si es diferente del patrocinador interno como en [Organización])
* Identificar al administrador del sistema, al administrador de la base de datos y al personal de soporte técnico para preguntas adicionales.
* Identificar a los analistas de mercado, expertos en minería de datos y estadísticos, y verificar su disponibilidad.
* Comprobar la disponibilidad de los expertos de dominio para las fases siguientes.

Recuerde que se puede necesitar personal técnico en momentos puntuales durante todo el proyecto, por ejemplo, durante la transformación de datos.

### Requisitos, suposiciones y restricciones
*Enumerar todos los requisitos del proyecto, incluyendo el cronograma de finalización, la comprensibilidad, la calidad de los resultados y la seguridad, así como los aspectos legales

*Listar las suposiciones hechas por el proyecto. Estos pueden ser supuestos sobre los datos, que pueden ser verificados durante la minería de datos, pero también pueden incluir supuestos no verificables relacionados con el proyecto. Es particularmente importante enumerar estos últimos si afectan a la validez de los resultados.

*Enumerar las limitaciones del proyecto. Estas limitaciones pueden incluir la falta de recursos para llevar a cabo algunas de las tareas del proyecto en el tiempo requerido, o pueden existir limitaciones legales o éticas en el uso de los datos o de la solución necesaria para llevar a cabo la tarea de minería de datos.

#### Requisitos
* Especificar el perfil del grupo objetivo
* Capturar todos los requisitos 
* Capturar los requisitos de comprensibilidad, precisión, despliegue, mantenimiento y reproducibilidad del proyecto de minería de datos y de los modelos resultantes.
* Capturar los requisitos de seguridad, restricciones legales, privacidad, informes y calendario del proyecto. 

#### Suposiciones
* Aclarar todas las suposiciones (incluidas las implícitas) y hacerlas explícitas (por ejemplo, para abordar la cuestión empresarial, es necesario un número mínimo de clientes con más de 50 años de edad).
* Listar las suposiciones sobre la calidad de los datos (por ejemplo, exactitud, disponibilidad)
* Listar las suposiciones sobre factores externos (por ejemplo, cuestiones económicas, productos de la competencia)
* Aclarar las suposiciones que conducen a cualquier  estimación (por ejemplo, se supone que el precio de una herramienta específica es inferior a 1.000 dólares).
* Listar todas las suposiciones con respecto a si es necesario entender, describir o explicar el modelo (por ejemplo, cómo se debe presentar el modelo y los resultados a la alta gerencia/patrocinador).  

**La lista de suposiciones también incluye las suposiciones iniciales del proyecto**

#### Restricciones
* Revisar las restricciones generales (por ejemplo, cuestiones legales, presupuesto, plazos y recursos).
* Revisar el acceso a las fuentes de datos (por ejemplo, restricciones de acceso, contraseña requerida).
* Revisar la accesibilidad técnica de los datos (sistemas operativos, sistema de gestión de datos, formato de archivo o base de datos).
* Comprobar las restricciones de presupuesto (costes fijos, costes de ejecución, etc.)

### Riesgos y Contingencias
Enumere los riesgos, es decir, los eventos que pueden ocurrir, que impactan el cronograma, el costo o el resultado. Enumerar los correspondientes planes de contingencia.
#### Identificar los riesgos
* Identificar los riesgos del negocio (por ejemplo, la competencia obtiene primero mejores resultados).
* Identificar los riesgos organizacionales (por ejemplo, el departamento que solicita el proyecto no tiene fondos para el proyecto).
* Identificar los riesgos financieros (por ejemplo, el financiamiento de las siguientes etapas depende de los resultados iniciales de la minería de datos).
* Identificar los riesgos técnicos
* Identificar los riesgos que dependen de los datos y de las fuentes de datos (por ejemplo, mala calidad).

#### Desarrollar planes de contingencia
* Determinar las condiciones bajo las cuales cada riesgo puede ocurrir
* Desarrollar planes de contingencia

### Terminología
Elaborar un glosario de terminología relevante para el proyecto. Esto debe incluir al menos dos componentes:  

1. Un glosario de terminología empresarial relevante, que forma parte del entendimiento empresarial disponible para el proyecto.
2. Un glosario de terminología de minería de datos, ilustrado con ejemplos relevantes para el problema empresarial en cuestión.  

* Verificar la existencia de glosarios previos; de lo contrario, comenzar a redactarlos.
* Hablar con los expertos de dominio para entender su terminología
* Familiarizarse con la terminología del negocio

### Beneficios y costos
Preparar un análisis de costo-beneficio para el proyecto, comparando los costos del proyecto con los beneficios potenciales para el negocio si es exitoso.

* Estimar los costos de la recolección de datos
* Estimar los costos de desarrollo e implementación de una solución
* Identificar los beneficios (por ejemplo, la mejora de la satisfacción del cliente, el retorno de la inversión y el aumento de los ingresos).
* Estimar los costos operativos

La comparación debe ser lo más específica posible, ya que esto permite presentar una mejor propuesta de negocio.  

**Recuerde identificar los costos ocultos, tales como la extracción y preparación repetida de datos, los cambios en los flujos de trabajo y el tiempo requerido para la capacitación.**

## Determinar los objetivos de la minería de datos
Una meta empresarial establece los objetivos en la terminología empresarial; una meta de minería de datos establece los objetivos del proyecto en términos técnicos. Por ejemplo, el objetivo empresarial podría ser, "Aumentar las ventas de catálogos a clientes existentes", mientras que el objetivo de la minería de datos podría ser, "Predecir cuántos productos comprará un cliente, dadas sus compras en los últimos tres años, la información demográfica relevante y el precio del artículo".

### Objetivos de la minería de datos
Describe los resultados previstos del proyecto que permitan alcanzar los objetivos de negocio. Tenga en cuenta que normalmente se trata de mensajes técnicos.

* Traducir las preguntas de negocio a objetivos de minería de datos (por ejemplo, una campaña de marketing requiere la segmentación de los clientes para decidir a quién dirigirse en esta campaña; se debe especificar el nivel/tamaño de los segmentos).
* Especificar el tipo de problema de minería de datos (por ejemplo, clasificación, descripción, predicción y agrupación). Para más detalles sobre los tipos de problemas de minería de datos, véase el Apéndice 2.

### Criterios de éxito para la minería de datos
Definir los criterios para un resultado exitoso del proyecto en términos técnicos, por ejemplo, un cierto nivel de precisión predictiva o un perfil de propensión a la compra con un determinado grado de "elevación". Al igual que con los criterios de éxito empresarial, puede ser necesario describirlos en términos subjetivos, en cuyo caso se debe identificar a la persona o personas que hacen el juicio subjetivo.

* Especificar los criterios para la evaluación del modelo (por ejemplo, la precisión, el rendimiento y la complejidad del modelo).
* Definir 'benchmarks' para los criterios de evaluación
* Especificar los criterios que se refieren a los criterios de evaluación subjetivos (por ejemplo, el modelo explica la capacidad y los datos y los conocimientos de marketing proporcionados por el modelo).

**Recuerde que los criterios de éxito de la minería de datos son diferentes a los criterios de éxito del negocio definidos anteriormente.**

Recuerde que es prudente planificar la implementación desde el inicio del proyecto.

## Generación del plan de proyecto
Describa el plan previsto para alcanzar los objetivos de la minería de datos y, por lo tanto, para alcanzar los objetivos del negocio.

### Plan de proyecto
Enumerar las etapas a ejecutar en el proyecto, junto con su duración, recursos requeridos, entradas, salidas y dependencias. Siempre que sea posible, explicite las iteraciones a gran escala en el proceso de minería de datos, por ejemplo, las repeticiones de las fases de modelado y evaluación. Como parte del plan del proyecto, también es importante analizar las dependencias entre el cronograma y los riesgos. Marque los resultados de estos análisis explícitamente en el plan del proyecto, idealmente con acciones y recomendaciones de acciones si los riesgos se manifiestan.

Aunque esta es la única tarea en la que se menciona directamente el plan del proyecto, debe ser consultado continuamente y revisado a lo largo de todo el proyecto. El plan de proyecto debe ser consultado como mínimo cada vez que se inicie una nueva tarea o se inicie una nueva iteración de una tarea o actividad.

* Definir el plan de proceso inicial y discutir la viabilidad con todo el personal involucrado.
* Combinar todos los objetivos identificados y las técnicas seleccionadas en un procedimiento coherente que resuelva las cuestiones de negocio y cumpla con los criterios de éxito del negocio.
* Estimar el esfuerzo y los recursos necesarios para lograr y desplegar la solución. (Es útil tener en cuenta la experiencia de otras personas al estimar las escalas de tiempo para los proyectos de minería de datos. Por ejemplo, a menudo se postula que entre el 50 y el 70 por ciento del tiempo y el esfuerzo de un proyecto de minería de datos se utiliza en la fase de preparación de datos y entre el 20 y el 30 por ciento en la fase de comprensión de datos, mientras que sólo entre el 10 y el 20 por ciento se gasta en cada una de las fases de modelado, evaluación y comprensión de negocios, y entre el 5 y el 10 por ciento en la fase de implementación).
* Identificar los pasos críticos
* Identificar los puntos de decisión
* Identificar los puntos de revisión
* Identificar las principales iteraciones

### Evaluación inicial de herramientas y técnicas
Al final de la primera fase, el equipo del proyecto realiza una evaluación inicial de las herramientas y técnicas. Aquí, es importante seleccionar una herramienta de minería de datos que soporte varios métodos para diferentes etapas del proceso, ya que la selección de herramientas y técnicas puede influir en todo el proyecto.

* Crear una lista de criterios de selección de herramientas y técnicas (o utilizar uno existente si está disponible).
* Elegir herramientas y técnicas potenciales
* Evaluar la idoneidad de las técnicas
* Revisar y priorizar las técnicas aplicables de acuerdo a la evaluación de soluciones alternativas.

# Comprensión de los datos

## Recopilación de datos iniciales
Adquirir los datos (o acceso a los datos) listados en los recursos del proyecto. Esta recopilación inicial incluye la carga de datos, si es necesario para el análisis. Por ejemplo, si tiene la intención de utilizar una herramienta específica para el análisis de datos, es lógico cargarlos en esta herramienta.

### Informe inicial de recopilación de datos
Describa todos los datos utilizados para el proyecto e incluya cualquier requisito de selección para obtener datos más detallados. El informe de recopilación de datos también debe definir si algunos atributos son relativamente más importantes que otros.

Recuerde que cualquier evaluación de la calidad de los datos debe hacerse no sólo de las fuentes de datos individuales, sino también de cualquier dato que resulte de la fusión entre fuentes de datos. Debido a las inconsistencias entre las fuentes, los datos fusionados pueden presentar problemas que no existen en las fuentes de datos individuales.

#### Data requirements planning
* Plan which information is needed (e.g., only for given attributes, or specific additional information)
* Check if all the information needed (to solve the data mining goals) is actually available

#### Selection criteria
* Specify selection criteria (e.g., Which attributes are necessary for the specified data mining goals? Which attributes have been identified as being irrelevant? How many attributes can we handle with the chosen techniques?)
* Select tables/files of interest
* Select data within a table/file
* Think about how long a history one should use (e.g., even if 18 months of data are available, only 12 months may be needed for the exercise)

**Be aware that data collected from different sources may give rise to quality problems when merged (e.g., address files merged with a customer database may show inconsistencies of format, invalidity of data, etc.).**

#### Insertion of data
* If the data contain free text entries, do we need to encode them for modeling or do we want to group specific entries?
* How can missing attributes be acquired?
* How can we best extract the data?

Remember that some knowledge about the data may be available from non-electronic sources (e.g., from people, printed text, etc.).

Remember that it may be necessary to preprocess the data (time-series data, weighted averages, etc.).

## Describe Data
Examine the “gross” properties of the acquired data and report on the results.

### Data Description Report
Describe the data that has been acquired, including the format of the data, the quantity of the data (e.g., the number of records and fields within each table), the identities of the fields, and any other surface features that have been discovered.

#### Volumetric analysis of data
* Identify data and method of capture
* Access data sources
* Use statistical analyses if appropriate
* Report tables and their relations
* Check data volume, number of multiples, complexity
* Note if the data contain free text entries

#### Attribute types and values
* Check accessibility and availability of attributes
* Check attribute types (numeric, symbolic, taxonomy, etc.)
* Check attribute value ranges
* Analyze attribute correlations
* Understand the meaning of each attribute and attribute value in business terms
* For each attribute, compute basic statistics (e.g., compute distribution, average, max, min, standard deviation, variance, mode, skewness, etc.)
* Analyze basic statistics and relate the results to their meaning in business terms
* Decide if the attribute is relevant for the specific data mining goal
* Determine if the attribute meaning is used consistently
* Interview domain experts to obtain their opinion of attribute relevance
* Decide if it is necessary to balance the data (based on the modeling techniques to be used)

#### Keys
* Analyze key relationships
* Check amount of overlaps of key attribute values across tables

#### Review assumptions/goals
* Update list of assumptions, if necessary

## Explore Data
This task tackles the data mining questions that can be addressed using querying, visualization, and reporting techniques. These analyses may directly address the data mining goals. However, they may also contribute to or refine the data description and quality reports, and feed into the transformation and other data preparation steps needed before further analysis can occur.

### Data Exploration Report
Describe the results of this task, including first findings or initial hypotheses and their impact on the remainder of the project. The report may also include graphs and plots that indicate data characteristics or point to interesting data subsets worthy of further examination.

#### Data exploration
* Analyze properties of interesting attributes in detail (e.g., basic statistics, interesting sub-populations)
* Identify characteristics of sub-populations

#### Form suppositions for future analysis
* Consider and evaluate information and findings in the data descriptions report
* Form a hypothesis and identify actions
* Transform the hypothesis into a data mining goal, if possible
* Clarify data mining goals or make them more precise. A “blind” search is not necessarily useless, but a more directed search toward business objectives is preferable.
* Perform basic analysis to verify the hypothesis

## Verify Data Quality
Examine the quality of the data, addressing questions such as: Is the data complete (does it cover all the cases required)? Is it correct or does it contain errors? If there are errors, how common are they? Are there missing values in the data? If so, how are they represented, where do they occur, and how common are they?

### Data Quality Report
List the results of the data quality verification; if there are quality problems, list possible solutions.

* Identify special values and catalog their meaning

#### Review keys, attributes
* Check coverage (e.g., whether all possible values are represented)
* Check keys
* Verify that the meanings of attributes and contained values fit together
* Identify missing attributes and blank fields
* Establish the meaning of missing data
* Check for attributes with different values that have similar meanings (e.g., low fat, diet)
* Check spelling and format of values (e.g., same value but sometimes beginning with a lower-case letter, sometimes with an upper-case letter)
* Check for deviations, and decide whether a deviation is “noise” or may indicate an interesting phenomenon
* Check for plausibility of values, (e.g., all fields having the same or nearly the same values)

Review any attributes that give answers that conflict with common sense (e.g., teenagers with high income levels).

Use visualization plots, histograms, etc. to reveal inconsistencies in the data.

#### Data quality in flat files
* If data are stored in flat files, check which delimiter is used and whether it is used consistently within all attributes
* If data are stored in flat files, check the number of fields in each record to see if they coincide

#### Noise and inconsistencies between sources
* Check consistencies and redundancies between different sources
* Plan for dealing with noise
* Detect the type of noise and which attributes are affected

Remember that it may be necessary to exclude some data since they do not exhibit either positive or negative behavior (e.g., to check on customers’ loan behavior, exclude all those who have never borrowed, do not finance a home mortgage, those whose mortgage is nearing maturity, etc.).

Review whether assumptions are valid or not, given the current information on data and business knowledge.

# Data Preparation
**Dataset:** These are the dataset(s) produced by the data preparation phase, used for modeling or for the major analysis work of the project.

**Dataset description:** This is the description of the dataset(s) used for the modeling or for the major analysis work of the project.

## Select Data
Decide on the data to be used for analysis. Criteria include relevance to the data mining goals, quality, and technical constraints such as limits on data volume or data types.

### Rationale for Inclusion/Exclusion
List the data to be used/excluded and the reasons for these decisions.

* Collect appropriate additional data (from different sources—in-house as well as externally)
* Perform significance and correlation tests to decide if fields should be included
* Reconsider Data Selection Criteria in light of experiences of data quality and data exploration (i.e., may wish include/exclude other sets of data)
* Reconsider Data Selection Criteria in light of experience of modeling (i.e., model assessment may show that other datasets are needed)
* Select different data subsets (e.g., different attributes, only data which meet certain conditions)
* Consider the use of sampling techniques (e.g., A quick solution may involve splitting test and training datasets or reducing the size of the test dataset, if the tool cannot handle the full dataset. It may also be useful to have weighted samples to give different importance to different attributes or different values of the same attribute.)
* Document the rationale for inclusion/exclusion
* Check available techniques for sampling data

Based on Data Selection Criteria, decide if one or more attributes are more important than others and weight the attributes accordingly. Decide, based on the context (i.e., application, tool, etc.), how to handle the weighting.

## Clean Data
Raise the data quality to the level required by the selected analysis techniques. This may involve the selection of clean subsets of the data, the insertion of suitable defaults, or more ambitious techniques such as the estimation of missing data by modeling.

### Data Cleaning Report
Describe the decisions and actions that were taken to address the data quality problems reported during the Verify Data Quality Task. If the data are to be used in the data mining exercise, the report should address outstanding data quality issues and what possible effect this could have on the results.

* Reconsider how to deal with any observed type of noise
* Correct, remove, or ignore noise
* Decide how to deal with special values and their meaning. The area of special values can give rise to many strange results and should be carefully examined. Examples of special values could arise through taking results of a survey where some questions were not asked or not answered. This might result in a value of 99 for unknown data. For example, 99 for marital status or political affiliation. Special values could also arise when data is truncated—e.g., 00 for 100-year-old people or all cars with 100,000 km on the odometer.
* Reconsider Data Selection Criteria in light of experiences of data cleaning (i.e., you may wish to include/exclude other sets of data).

Remember that some fields may be irrelevant to the data mining goals and, therefore, noise in those fields has no significance. However, if noise is ignored for these reasons, it should be fully documented as the circumstances may change later.

## Construct Data
This task includes constructive data preparation operations such as the production of derived attributes, complete new records, or transformed values for existing attributes.

* Check available construction mechanisms with the list of tools suggested for the project
* Decide whether it is best to perform the construction inside the tool or outside (i.e., which is more efficient, exact, repeatable)
* Reconsider Data Selection Criteria Data Selection Criteria in light of experiences of data construction (i.e., you may wish include/exclude other sets of data)

### Derived Attributes
Derived attributes are new attributes that are constructed from one or more existing attributes in the same record. An example might be: area = length * width.

Why should we need to construct derived attributes during the course of a data mining investigation? It should not be thought that only data from databases or other sources should be used in constructing a model. Derived attributes might be constructed because:

* Background knowledge convinces us that some fact is important and ought to be represented although we have no attribute currently to represent it
* The modeling algorithm in use handles only certain types of data—for example we are using linear regression and we suspect that there are certain non-linearities that will be not be included in the model
* The outcome of the modeling phase suggests that certain facts are not being covered

#### Derived attributes
* Decide if any attribute should be normalized (e.g., when using a clustering algorithm with age and income, in certain currencies, the income will dominate)
* Consider adding new information on the relevant importance of attributes by adding new attributes (for example, attribute weights, weighted normalization)
* How can missing attributes be constructed or imputed? [Decide type of construction (e.g., aggregate, average, induction).]
* Add new attributes to the accessed data

Before adding Derived Attributes, try to determine if and how they ease the model process or facilitate the modeling algorithm. Perhaps “income per person” is a better/easier attribute to use than “income per household.” Do not derive attributes simply to reduce the number of input attributes.

Another type of derived attribute is the single-attribute transformation, usually performed to fit the needs of the modeling tools.

#### Single-attribute transformations
* Specify necessary transformation steps in terms of available transformation facilities (for example, change a binning of a numeric attribute)
* Perform transformation steps

Transformations may be necessary to change ranges to symbolic fields (e.g., ages to age ranges) or symbolic fields (“definitely yes,” “yes,” “don’t know,” “no”) to numeric values. Modeling tools or algorithms often require them.

### Generated Records
Generated records are completely new records, which add new knowledge or represent new data that is not otherwise represented (e.g., having segmented the data, it may be useful to generate a record to represent the prototypical member of each segment for further processing).

Check for available techniques if needed (e.g., mechanisms to construct prototypes for each segment of segmented data).

## Integrate Data
These are methods for combining information from multiple tables or other information sources to create new records or values.

### Merged Data
Merging tables refers to joining together two or more tables that have different information about the same objects. At this stage, it may also be advisable to generate new records. It may also be recommended to generate aggregate values.

Aggregation refers to operations where new values are computed by summarizing information from multiple records and/or tables.

* Check if integration facilities are able to integrate the input sources as required
* Integrate sources and store results
* Reconsider Data Selection Criteria in light of experiences of data integration (i.e., you may wish to include/exclude other sets of data)

Remember that some knowledge may be contained in non-electronic format.

## Format Data
Formatting transformations refers primarily to syntactic modifications made to the data that do not change its meaning, but might be required by the modeling tool.

### Reformatted Data
Some tools have requirements on the order of the attributes, such as the first field being a unique identifier for each record or the last field being the outcome field the model is to predict.

#### Rearranging attributes
Some tools have requirements on the order of the attributes, such as the first field being a unique identifier for each record or the last field being the outcome field the model is to predict.

#### Reordering records
It might be important to change the order of the records in the dataset. Perhaps the modeling tool requires that the records be sorted according to the value of the outcome attribute.

#### Reformatted within-value
* These are purely syntactic changes made to satisfy the requirements of the specific modeling tool
* Reconsider Data Selection Criteria in light of experiences of data cleaning (i.e., you may wish to include/exclude other sets of data)

## Dataset
These are the dataset(s) produced by the data preparation phase, used for modeling or for the major analysis work of the project.

### Dataset Description
This is the description of the dataset(s) used for the modeling or for the major analysis work of the project.

# Modeling

## Select Modeling Techniques
As the first step in modeling, select the actual initial modeling technique. If multiple techniques are to be applied, perform this task separately for each technique.

Remember that not all tools and techniques are applicable to each and every task. For certain problems, only some techniques are appropriate (See Appendix 2, where techniques appropriate for certain data mining problem types are discussed in more detail). “Political requirements” and other constraints further limit the choices available to the data mining engineer. It may be that only one tool or technique is available to solve the problem at hand—and that the tool may not be absolutely the best, from a technical standpoint.

### Modeling Technique
Record the actual modeling technique that is used.

Decide on appropriate technique for exercise, bearing in mind the tool selected.

### Modeling Assumptions
Many modeling techniques make specific assumptions about the data.

* Define any built-in assumptions made by the technique about the data (e.g., quality, format, distribution)
* Compare these assumptions with those in the Data Description Report
* Make sure that these assumptions hold and go back to the Data Preparation Phase, if necessary

## Generate Test Design
Prior to building a model, it is necessary to define a procedure to test the model’s quality and validity. For example, in supervised data mining tasks such as classification, it is common to use error rates as quality measures for data mining models. Therefore, the test design specifies that the dataset should be separated into training and test sets. The model is built on the training set and its quality estimated on the test set.

### Test Design
Describe the intended plan for training, testing, and evaluating the models. A primary component of the plan is to decide how to divide the available dataset into training data, test data, and validation test sets.

* Check existing test designs for each data mining goal separately
* Decide on necessary steps (number of iterations, number of folds, etc.)
* Prepare data required for test

## Build Model
Run the modeling tool on the prepared dataset to create one or more models.

### Parameter Settings
With any modeling tool, there are often a large number of parameters that can be adjusted. List the parameters and their chosen values, along with the rationale for the choice.

* Set initial parameters
* Document reasons for choosing those values

### Models
Run the modeling tool on the prepared dataset to create one or more models.

* Run the selected technique on the input dataset to produce the model
* Post-process data mining results (e.g., edit rules, display trees)

### Model Description
Describe the resulting model and assess its expected accuracy, robustness, and possible shortcomings. Report on the interpretation of the models and any difficulties encountered.

* Describe any characteristics of the current model that may be useful for the future
* Record parameter settings used to produce the model
* Give a detailed description of the model and any special features
* For rule-based models, list the rules produced, plus any assessment of per-rule or overall model accuracy and coverage
* For opaque models, list any technical information about the model (such as neural network topology) and any behavioral descriptions produced by the modeling process (such as accuracy or sensitivity)
* Describe the model’s behavior and interpretation
* State conclusions regarding patterns in the data (if any); sometimes the model reveals important facts about the data without a separate assessment process (e.g., that the output or conclusion is duplicated in one of the inputs)

## Assess Model
The model should now be assessed to ensure that it meets the data mining success criteria and passes the desired test criteria. This is a purely technical assessment based on the outcome of the modeling tasks.

### Model Assessment
Summarize results of this task, list qualities of generated models (e.g., in terms of accuracy), and rank their quality in relation to each other.

* Evaluate results with respect to evaluation criteria
* Test result according to a test strategy (e.g.: Train and Test, Cross-validation, bootstrapping, etc.)
* Compare evaluation results and interpretation
* Create ranking of results with respect to success and evaluation criteria
* Select best models
* Interpret results in business terms (as far as possible at this stage)
* Get comments on models by domain or data experts
* Check plausibility of model
* Check effect on data mining goal
* Check model against given knowledge base to see if the discovered information is novel and useful
* Check reliability of result
* Analyze potential for deployment of each result
* If there is a verbal description of the generated model (e.g., via rules), assess the rules: Are they logical, are they feasible, are there too many or too few, do they offend common sense?
* Assess results
* Get insights into why a certain modeling technique and certain parameter settings lead to good/bad results

“Lift Tables” and “Gain Tables” can be constructed to determine how well the model is predicting.

### Revised Parameter Settings
According to the model assessment, revise parameter settings and tune them for the next run in the Build Model task. Iterate model building and assessment until you find the best model.

Adjust parameters to produce better models.

# Evaluation
Previous evaluation steps dealt with factors such as the accuracy and generality of the model. This step assesses the degree to which the model meets the business objectives, and seeks to determine if there is some business reason why this model is deficient. It compares results with the evaluation criteria defined at the start of the project.

A good way of defining the total outputs of a data mining project is to use the equation:
$$RESULTS = MODELS + FINDINGS$$

In this equation, we are defining that the total output of the data mining project is not just the models (although they are, of course, important) but also the findings, which we define as anything (apart from the model) that is important in meeting the objectives of the business or important in leading to new questions, lines of approach, or side effects (e.g., data quality problems uncovered by the data mining exercise). Note: Although the model is directly connected to the business questions, the findings need not be related to any questions or objectives, as long as they are important to the initiator of the project.

## Evaluate Results
This step assesses the degree to which the model meets the business objectives, and seeks to determine if there is some business reason why this model is deficient. Another option is to test the model(s) on test applications in the real application, if time and budget constraints permit.

Moreover, evaluation also assesses other generated data mining results. Data mining results cover models that are related to the original business objectives and all other findings. Some are related to the original business objectives while others might unveil additional challenges, information, or hints for future directions.

### Assessment of Data Mining Results w.r.t. Business Success Criteria
Summarize assessment results in terms of business success criteria, including a final statement related to whether the project already meets the initial business objectives.

* Understand the data mining results
* Interpret the results in terms of the application
* Check effect on for data mining goal
* Check the data mining result against the given knowledge base to see if the discovered information is novel and useful
* Evaluate and assess results with respect to business success criteria (i.e., has the project achieved the original Business Objectives)
* Compare evaluation results and interpretation
* Rank results with respect to business success criteria
* Check effect of result on initial application goal
* Determine if there are new business objectives to be addressed later in the project, or in new projects
* State recommendations for future data mining projects

### Approved Models
After accessing models with respect to business success criteria, select and approve the generated models that meet the selected criteria.

## Review Process
At this point, the resulting model appears to be satisfactory and appears to satisfy business needs. It is now appropriate to make a more thorough review of the data mining engagement in order to determine if there is any important factor or task that has somehow been overlooked. At this stage of the data mining exercise, the Process Review takes the form of a Quality Assurance Review.

### Review of Process
Summarize the process review and list activities that have been missed and/or should be repeated.

* Provide an overview of the data mining process used
* Analyze the data mining process. For each stage of the process ask:
    + Was it necessary?
    + Was it executed optimally?
    + In what ways could it be improved?
* Identify failures
* Identify misleading steps
* Identify possible alternative actions and/or unexpected paths in the process
* Review data mining results with respect to business success criteria

## Determine Next Steps
Based on the assessment results and the process review, the project team decides how to proceed. Decisions to be made include whether to finish this project and move on to deployment, to initiate further iterations, or to set up new data mining projects.

### List of Possible Actions
List possible further actions along with the reasons for and against each option.

* Analyze the potential for deployment of each result
* Estimate potential for improvement of current process
* Check remaining resources to determine if they allow additional process iterations (or whether additional resources can be made available)
* Recommend alternative continuations
* Refine process plan

### Decision
Describe the decisions made, along with the rationale for them.

* Rank the possible actions
* Select one of the possible actions
* Document reasons for the choice

# Deployment

## Plan Deployment
This task starts with the evaluation results and concludes with a strategy for deployment of the data mining result(s) into the business.

### Deployment Plan
Summarize the deployment strategy, including necessary steps and how to perform them.

* Summarize deployable results
* Develop and evaluate alternative plans for deployment
* Decide for each distinct knowledge or information result
* Determine how knowledge or information will be propagated to users
* Decide how the use of the result will be monitored and its benefits measured (where applicable)
* Decide for each deployable model or software result
* Establish how the model or software result will be deployed within the organization’s systems
* Determine how its use will be monitored and its benefits measured (where applicable)
* Identify possible problems during deployment (pitfalls to be avoided)

## Plan Monitoring and Maintenance
Monitoring and maintenance are important issues if the data mining results become part of the day-to-day business and its environment. A careful preparation of a maintenance strategy helps to avoid unnecessarily long periods of incorrect usage of data mining results. In order to monitor the deployment of the data mining result(s), the project needs a detailed plan for monitoring and maintenance. This plan takes into account the specific type of deployment.

### Monitoring and Maintenance Plan
Summarize monitoring and maintenance strategy, including necessary steps and how to perform them.

* Check for dynamic aspects (i.e., what things could change in the environment?)
* Decide how accuracy will be monitored
* Determine when the data mining result or model should not be used any more. Identify criteria (validity, threshold of accuracy, new data, change in the application domain, etc.), and what should happen if the model or result could no longer be used. (update model, set up new data mining project, etc.).
* Will the business objectives of the use of the model change over time? Fully document the initial problem the model was attempting to solve.
* Develop monitoring and maintenance plan.

## Produce Final Report
At the end of the project, the project team writes up a final report. Depending on the deployment plan, this report may be only a summary of the project and its experience, or a final presentation of the data mining result(s).

### Final Report
At the end of the project, there will be at least one final report in which all the threads are brought together. As well as identifying the results obtained, the report should also describe the process, show which costs have been incurred, define any deviations from the original plan, describe implementation plans, and make any recommendations for future work. The actual detailed content of the report depends very much on the intended audience.

* Identify what reports are needed (slide presentation, management summary, detailed findings, explanation of models, etc.)
* Analyze how well initial data mining goals have been met
* Identify target groups for report
* Outline structure and contents of report(s)
* Select findings to be included in the reports
* Write a report

### Final Presentation
As well as a final report, it may be necessary to make a final presentation to summarize the project -- maybe to the management sponsor, for example. The presentation normally contains a subset of the information contained in the final report, structured in a different way.

* Decide on target group for the final presentation and determine if they will already have received the final report
* Select which items from the final report should be included in final presentation

## Review Project
Assess what went right and what went wrong, what was done well, and what needs to be improved.

### Experience Documentation
Summarize important experience gained during the project. For example, pitfalls, misleading approaches, or tips for selecting the best-suited data mining techniques in similar situations could be part of this documentation. In ideal projects, experience documentation also covers any reports that have been written by individual project members during the project.

* Interview all significant people involved in the project and ask them about their experience during the project
* If end users in the business work with the data mining result(s), interview them: Are they satisfied? What could have been done better? Do they need additional support?
* Summarize feedback and write the experience documentation
* Analyze the process (things that worked well, mistakes made, lessons learned, etc.)
* Document the specific data mining process (How can the results and the experience of applying the model be fed back into the process?)
* Generalize from the details to make the experience useful for future projects